// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.DBContext;

#nullable disable

namespace ConsoleDB.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241212201847_InitialMigrate´")]
    partial class InitialMigrate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Entities.AnlageTyp", b =>
                {
                    b.Property<int>("Typ_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Typ_Id"));

                    b.Property<double>("BandBreite")
                        .HasColumnType("double precision");

                    b.Property<double>("SchenkelZahl")
                        .HasColumnType("double precision");

                    b.Property<double>("SchichtHöhe")
                        .HasColumnType("double precision");

                    b.Property<double>("Toleranz")
                        .HasColumnType("double precision");

                    b.HasKey("Typ_Id");

                    b.ToTable("AnlageTyp");
                });
#pragma warning restore 612, 618
        }
    }
}
