// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrenchAPI.Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(WebDbContext))]
    [Migration("20251210113322_RenameToDBMLSchema")]
    partial class RenameToDBMLSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrenchAPI.Core.Entities.Messeinstellung", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("name");

                    b.Property<int>("sonden_pro_schenkel")
                        .HasColumnType("integer")
                        .HasColumnName("sonden_pro_schenkel");

                    b.Property<int>("sondentyp_id")
                        .HasColumnType("integer")
                        .HasColumnName("sondentyp_id");

                    b.Property<int>("spule_id")
                        .HasColumnType("integer")
                        .HasColumnName("spule_id");

                    b.HasKey("ID");

                    b.HasIndex("sondentyp_id");

                    b.HasIndex("spule_id");

                    b.ToTable("messeinstellung");
                });

            modelBuilder.Entity("TrenchAPI.Core.Entities.Messung", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("anfangszeitpunkt")
                        .HasColumnType("timestamp")
                        .HasColumnName("anfangszeitpunkt");

                    b.Property<DateTime>("endzeitpunkt")
                        .HasColumnType("timestamp")
                        .HasColumnName("endzeitpunkt");

                    b.Property<int>("messeinstellung_id")
                        .HasColumnType("integer")
                        .HasColumnName("messeinstellung_id");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("name");

                    b.Property<string>("notiz")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("notiz");

                    b.Property<decimal>("pruefspannung")
                        .HasColumnType("decimal")
                        .HasColumnName("pruefspannung");

                    b.Property<decimal>("tauchkernstellung")
                        .HasColumnType("decimal")
                        .HasColumnName("tauchkernstellung");

                    b.HasKey("ID");

                    b.HasIndex("messeinstellung_id");

                    b.ToTable("messung");
                });

            modelBuilder.Entity("TrenchAPI.Core.Entities.Messwert", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("messung_id")
                        .HasColumnType("integer")
                        .HasColumnName("messung_id");

                    b.Property<int>("sondenposition_id")
                        .HasColumnType("integer")
                        .HasColumnName("sondenposition_id");

                    b.Property<decimal>("wert")
                        .HasColumnType("decimal")
                        .HasColumnName("wert");

                    b.Property<DateTime>("zeitpunkt")
                        .HasColumnType("timestamp")
                        .HasColumnName("zeitpunkt");

                    b.HasKey("ID");

                    b.HasIndex("messung_id");

                    b.HasIndex("sondenposition_id");

                    b.ToTable("messwert");
                });

            modelBuilder.Entity("TrenchAPI.Core.Entities.Sonde", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<decimal>("kalibrierungsfaktor")
                        .HasColumnType("decimal")
                        .HasColumnName("kalibrierungsfaktor");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("name");

                    b.Property<int>("sondentyp_id")
                        .HasColumnType("integer")
                        .HasColumnName("sondentyp_id");

                    b.HasKey("ID");

                    b.HasIndex("sondentyp_id");

                    b.ToTable("sonde");
                });

            modelBuilder.Entity("TrenchAPI.Core.Entities.SondenPosition", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("messeinstellung_id")
                        .HasColumnType("integer")
                        .HasColumnName("messeinstellung_id");

                    b.Property<int>("position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<int>("schenkel")
                        .HasColumnType("integer")
                        .HasColumnName("schenkel");

                    b.Property<int>("sonde_id")
                        .HasColumnType("integer")
                        .HasColumnName("sonde_id");

                    b.HasKey("ID");

                    b.HasIndex("messeinstellung_id");

                    b.HasIndex("sonde_id");

                    b.ToTable("sondenposition");
                });

            modelBuilder.Entity("TrenchAPI.Core.Entities.SondenTyp", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<decimal>("alpha")
                        .HasColumnType("decimal")
                        .HasColumnName("alpha");

                    b.Property<decimal>("breite")
                        .HasColumnType("decimal")
                        .HasColumnName("breite");

                    b.Property<decimal>("hoehe")
                        .HasColumnType("decimal")
                        .HasColumnName("hoehe");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("name");

                    b.Property<string>("notiz")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("notiz");

                    b.Property<int>("windungszahl")
                        .HasColumnType("integer")
                        .HasColumnName("windungszahl");

                    b.HasKey("ID");

                    b.ToTable("sondentyp");
                });

            modelBuilder.Entity("TrenchAPI.Core.Entities.Spule", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("auftragsnr")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("auftragsnr");

                    b.Property<int>("auftragsposnr")
                        .HasColumnType("integer")
                        .HasColumnName("auftragsposnr");

                    b.Property<decimal>("bemessungsfrequenz")
                        .HasColumnType("decimal")
                        .HasColumnName("bemessungsfrequenz");

                    b.Property<decimal>("bemessungsspannung")
                        .HasColumnType("decimal")
                        .HasColumnName("bemessungsspannung");

                    b.Property<string>("einheit")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("einheit");

                    b.Property<string>("notiz")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("notiz");

                    b.Property<int>("spuletyp_id")
                        .HasColumnType("integer")
                        .HasColumnName("spuletyp_id");

                    b.HasKey("ID");

                    b.HasIndex("spuletyp_id");

                    b.ToTable("spule");
                });

            modelBuilder.Entity("TrenchAPI.Core.Entities.SpuleTyp", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<decimal>("bandbreite")
                        .HasColumnType("decimal")
                        .HasColumnName("bandbreite");

                    b.Property<decimal>("durchmesser")
                        .HasColumnType("decimal")
                        .HasColumnName("durchmesser");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("name");

                    b.Property<string>("notiz")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("notiz");

                    b.Property<int>("schenkelzahl")
                        .HasColumnType("integer")
                        .HasColumnName("schenkelzahl");

                    b.Property<decimal>("schichthoehe")
                        .HasColumnType("decimal")
                        .HasColumnName("schichthoehe");

                    b.Property<decimal>("toleranzbereich")
                        .HasColumnType("decimal")
                        .HasColumnName("toleranzbereich");

                    b.HasKey("ID");

                    b.ToTable("spulentyp");
                });

            modelBuilder.Entity("TrenchAPI.Core.Entities.Messeinstellung", b =>
                {
                    b.HasOne("TrenchAPI.Core.Entities.SondenTyp", "SondenTyp")
                        .WithMany()
                        .HasForeignKey("sondentyp_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrenchAPI.Core.Entities.Spule", "Spule")
                        .WithMany()
                        .HasForeignKey("spule_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SondenTyp");

                    b.Navigation("Spule");
                });

            modelBuilder.Entity("TrenchAPI.Core.Entities.Messung", b =>
                {
                    b.HasOne("TrenchAPI.Core.Entities.Messeinstellung", "Messeinstellung")
                        .WithMany()
                        .HasForeignKey("messeinstellung_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Messeinstellung");
                });

            modelBuilder.Entity("TrenchAPI.Core.Entities.Messwert", b =>
                {
                    b.HasOne("TrenchAPI.Core.Entities.Messung", "Messung")
                        .WithMany()
                        .HasForeignKey("messung_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrenchAPI.Core.Entities.SondenPosition", "SondenPosition")
                        .WithMany()
                        .HasForeignKey("sondenposition_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Messung");

                    b.Navigation("SondenPosition");
                });

            modelBuilder.Entity("TrenchAPI.Core.Entities.Sonde", b =>
                {
                    b.HasOne("TrenchAPI.Core.Entities.SondenTyp", "SondenTyp")
                        .WithMany()
                        .HasForeignKey("sondentyp_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SondenTyp");
                });

            modelBuilder.Entity("TrenchAPI.Core.Entities.SondenPosition", b =>
                {
                    b.HasOne("TrenchAPI.Core.Entities.Messeinstellung", "Messeinstellung")
                        .WithMany()
                        .HasForeignKey("messeinstellung_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrenchAPI.Core.Entities.Sonde", "Sonde")
                        .WithMany()
                        .HasForeignKey("sonde_id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Messeinstellung");

                    b.Navigation("Sonde");
                });

            modelBuilder.Entity("TrenchAPI.Core.Entities.Spule", b =>
                {
                    b.HasOne("TrenchAPI.Core.Entities.SpuleTyp", "SpuleTyp")
                        .WithMany()
                        .HasForeignKey("spuletyp_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpuleTyp");
                });
#pragma warning restore 612, 618
        }
    }
}
