// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrenchAPI.Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(WebDbContext))]
    [Migration("20260204083820_InitialMigrate")]
    partial class InitialMigrate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrenchAPI.Core.Entities.Messeinstellung", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<int>("SondenProSchenkel")
                        .HasColumnType("int");

                    b.Property<int>("SondenTypID")
                        .HasColumnType("integer");

                    b.Property<int>("SpuleID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("SondenTypID");

                    b.HasIndex("SpuleID");

                    b.ToTable("Messeinstellung");
                });

            modelBuilder.Entity("TrenchAPI.Core.Entities.Messung", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Anfangszeitpunkt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Endzeitpunkt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MesseinstellungID")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<string>("Notiz")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<decimal>("Pruefspannung")
                        .HasColumnType("decimal");

                    b.Property<decimal>("Tauchkernstellung")
                        .HasColumnType("decimal");

                    b.HasKey("ID");

                    b.HasIndex("MesseinstellungID");

                    b.ToTable("Messung");
                });

            modelBuilder.Entity("TrenchAPI.Core.Entities.Messwert", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("MessungID")
                        .HasColumnType("integer");

                    b.Property<int>("SondenPositionID")
                        .HasColumnType("integer");

                    b.Property<decimal>("Wert")
                        .HasColumnType("decimal");

                    b.Property<DateTime>("Zeitpunkt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ID");

                    b.HasIndex("MessungID")
                        .HasDatabaseName("IX_Messwert_MessungID");

                    b.HasIndex("SondenPositionID")
                        .HasDatabaseName("IX_Messwert_SondenPositionID");

                    b.HasIndex("MessungID", "Zeitpunkt")
                        .HasDatabaseName("IX_Messwert_MessungID_Zeitpunkt");

                    b.ToTable("Messwert");
                });

            modelBuilder.Entity("TrenchAPI.Core.Entities.Sonde", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<decimal>("Kalibrierungsfaktor")
                        .HasColumnType("decimal");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<int>("SondenTypID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("SondenTypID");

                    b.ToTable("Sonde");
                });

            modelBuilder.Entity("TrenchAPI.Core.Entities.SondenPosition", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("MesseinstellungID")
                        .HasColumnType("integer");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("Schenkel")
                        .HasColumnType("int");

                    b.Property<int?>("SondeID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("MesseinstellungID");

                    b.HasIndex("SondeID");

                    b.ToTable("SondenPosition");
                });

            modelBuilder.Entity("TrenchAPI.Core.Entities.SondenTyp", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<decimal>("Alpha")
                        .HasColumnType("decimal");

                    b.Property<decimal>("Breite")
                        .HasColumnType("decimal");

                    b.Property<decimal>("Hoehe")
                        .HasColumnType("decimal");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<string>("Notiz")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<int>("Windungszahl")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("SondenTyp");
                });

            modelBuilder.Entity("TrenchAPI.Core.Entities.Spule", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("AuftragsPosNr")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<string>("Auftragsnr")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<decimal>("Bemessungsfrequenz")
                        .HasColumnType("decimal");

                    b.Property<decimal>("Bemessungsspannung")
                        .HasColumnType("decimal");

                    b.Property<string>("Einheit")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<string>("Notiz")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<int>("SpuleTypID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("SpuleTypID");

                    b.ToTable("Spule");
                });

            modelBuilder.Entity("TrenchAPI.Core.Entities.SpuleTyp", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<decimal>("Bandbreite")
                        .HasColumnType("decimal");

                    b.Property<decimal>("Durchmesser")
                        .HasColumnType("decimal");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notiz")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Schenkelzahl")
                        .HasColumnType("int");

                    b.Property<decimal>("Schichthoehe")
                        .HasColumnType("decimal");

                    b.Property<decimal>("Toleranzbereich")
                        .HasColumnType("decimal");

                    b.HasKey("ID");

                    b.ToTable("SpuleTyp");
                });

            modelBuilder.Entity("TrenchAPI.Core.Entities.Messeinstellung", b =>
                {
                    b.HasOne("TrenchAPI.Core.Entities.SondenTyp", "SondenTyp")
                        .WithMany()
                        .HasForeignKey("SondenTypID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrenchAPI.Core.Entities.Spule", "Spule")
                        .WithMany()
                        .HasForeignKey("SpuleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SondenTyp");

                    b.Navigation("Spule");
                });

            modelBuilder.Entity("TrenchAPI.Core.Entities.Messung", b =>
                {
                    b.HasOne("TrenchAPI.Core.Entities.Messeinstellung", "Messeinstellung")
                        .WithMany()
                        .HasForeignKey("MesseinstellungID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Messeinstellung");
                });

            modelBuilder.Entity("TrenchAPI.Core.Entities.Messwert", b =>
                {
                    b.HasOne("TrenchAPI.Core.Entities.Messung", "Messung")
                        .WithMany()
                        .HasForeignKey("MessungID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrenchAPI.Core.Entities.SondenPosition", "SondenPosition")
                        .WithMany()
                        .HasForeignKey("SondenPositionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Messung");

                    b.Navigation("SondenPosition");
                });

            modelBuilder.Entity("TrenchAPI.Core.Entities.Sonde", b =>
                {
                    b.HasOne("TrenchAPI.Core.Entities.SondenTyp", "SondenTyp")
                        .WithMany()
                        .HasForeignKey("SondenTypID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SondenTyp");
                });

            modelBuilder.Entity("TrenchAPI.Core.Entities.SondenPosition", b =>
                {
                    b.HasOne("TrenchAPI.Core.Entities.Messeinstellung", "Messeinstellung")
                        .WithMany()
                        .HasForeignKey("MesseinstellungID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrenchAPI.Core.Entities.Sonde", "Sonde")
                        .WithMany()
                        .HasForeignKey("SondeID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Messeinstellung");

                    b.Navigation("Sonde");
                });

            modelBuilder.Entity("TrenchAPI.Core.Entities.Spule", b =>
                {
                    b.HasOne("TrenchAPI.Core.Entities.SpuleTyp", "SpuleTyp")
                        .WithMany()
                        .HasForeignKey("SpuleTypID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpuleTyp");
                });
#pragma warning restore 612, 618
        }
    }
}
