= Project Usage

link:/01-projekte-2025-4chif-syp-trench/[Trench Project] / link:/01-projekte-2025-4chif-syp-trench/project_description/[Project Description] / *Usage*

== Benutzerrollen

Es gibt zwei verschiedene Benutzerrollen in der Anwendung:
- *Admin*: Hat vollen Zugriff auf alle Funktionen der Anwendung, einschließlich der Verwaltung von Benutzern und deren Berechtigungen. Erfordert eine Authentifizierung mit einem Passwort.
- *Monteur*: Hat vollen Zugriff auf alle Funktionen der Anwendung, jedoch sind Spulentypen und Sensortypen schreibgeschützt.

== Entitäten

Bevor Messungen erstellt werden können, müssen folgende Entitäten erstellt werden:
- *Spulentyp*: Ein allgemeiner Typ einer Spule, inklusive Schenkelzahl, Bandbreite, Schichthöhe, Durchmessers und eines Toleranzbereiches, 
  der die maximal akzeptable Abweichung der Spule angibt. 
- *Spule*: Eine konkrete Spule eines bestimmten Spulentypen, inklusive Auftragsnummer, AuftragsPosNummer, Bemessungsspannung und -frequenz, Einheit.
- *Sondentyp*: Ein allgemeiner Typ einer Messsonde, inklusive Breite, Höhe und einer Windungszahl.
- *Sonde*: Eine konkrete Messsonde eines bestimmten Sondentyps, inklusive eines optionalen Kalibrierungsfaktors.
- *Messeinstellung*: Eine Konfiguration für eine Messung. Hier muss die Spule angegegeben werden und die nötigen Sonden. 

== Messungen

Um eine Messung durchzuführen, muss eine *Messeinstellung* ausgewählt werden. Es müssen auch die Tauchkernstellung und die Prüfspannung angegeben werden. 

Wenn eine Messung gestartet ist, werden die Messwerte mit Visualisierung in Echtzeit angezeigt. Es kann nur eine Messung gleichzeitig durchgeführt werden, jedoch ist diese Messung global für jeden Nutzer zugänglich, und es kann über den global sichtbaren "Laufende Messung"-Button darauf zugegriffen werden.

Bei einer laufenden Messung besteht die Möglichkeit, die Messung zu pausieren, abzubrechen oder zu speichern. Falls nicht abgebrochen wird, wird die Messung in der Datenbank gespeichert und kann auch später abgerufen werden. 

In der Visualisierung wird die aktuelle Ausrichtung aller Schenkel angezeigt, wichtig hierbei ist der finale Vektor, welcher anzeigt, in welche Richtung die Auslenkung der Spule zeigt. Hierbei wird auch angezeigt, ob sich dieser Auslenkungsvektor in der im Spulentypen definierten Toleranzbereich befindet. 