[plantuml, format="svg"]
----
@startuml

entity SpulenTyp {
  + ID : integer <<PK>>
  --
  Name : varchar
  Schenkelanzahl : integer
  Bandbreite : decimal
  Schichthöhe : decimal
  Durchmesser : decimal
}

entity Spule {
  + ID : integer <<PK>>
  --
  SpulenTypID : integer <<FK>>
  AuftragsNr : varchar
  AuftragsPosNr : integer
  UR : decimal
  Einheit : integer
  Omega : decimal
}

entity Messung {
  + ID : integer <<PK>>
  --
  SpuleID : integer <<FK>>
  Summe : decimal
  Zeit : timestamp
}

entity Messeinstellung {
  + ID : integer <<PK>>
  --
  MessungID : integer <<FK>>
  Bemessunngsspannung : decimal
  Bemessungsfrequenz : decimal
  Sensoren : integer
  Toleranz : integer
}

entity Sensor {
  + ID : integer <<PK>>
  --
  SensorTypID : integer <<FK>>
  MessungID : integer <<FK>>
  Schenkel : integer
  Position : integer
  Wert : decimal
  Zeit : timestamp
}

entity SensorTyp {
  + ID : integer <<PK>>
  --
  Wicklungszahl : integer
}

SpulenTyp ||--|{ Spule : "defines"
Spule ||--|{ Messung : "records"
Messung ||--|{ Messeinstellung : "configured with"
Messung ||--|{ Sensor : "has"
SensorTyp ||--|{ Sensor : "used by"

@enduml
