// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrenchAPI.Models;

#nullable disable

namespace TrenchAPI.Migrations
{
    [DbContext(typeof(SpuleContext))]
    [Migration("20250103211148_First Migration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrenchAPI.Models.Spule", b =>
                {
                    b.Property<int>("SpuleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SpuleID"));

                    b.Property<int>("AuftragsPosNr")
                        .HasColumnType("int");

                    b.Property<int>("Auftragsnummer")
                        .HasColumnType("int");

                    b.Property<int>("Einheit")
                        .HasColumnType("int");

                    b.Property<decimal>("Ur")
                        .HasColumnType("decimal(8,3)");

                    b.Property<decimal>("omega")
                        .HasColumnType("decimal(8,5)");

                    b.HasKey("SpuleID");

                    b.ToTable("Spule");
                });
#pragma warning restore 612, 618
        }
    }
}
